### ISSUE TITLE
FMIndex::getNumStrings returns one more than expected

### ISSUE THREAD

**Issue by sjackman** [jts/dbgfm#3]
Hi Jared,

Because BWTDiskReader maps the EOF symbol to a '$', `count_map['$']` returns the number of strings plus one, and getNumStrings returns one more than expected. It's easy enough to fix, but I wanted to check that your work doesn't depend on this behaviour before I mucked with it.

https://github.com/jts/dbgfm/blob/master/bwtdisk_reader.cpp#L65
https://github.com/jts/dbgfm/blob/master/fm_index_builder.cpp#L81

Cheers,
Shaun

**Comment by jts** [comment]
Hi Shaun,

Yes this is a bug. I don't think anything relies on the incorrect behaviour
so feel free to change it.

Jared

**Comment by sjackman** [comment]
@rchikhi Hi, Rayan. I fixed a small off-by-one bug in jts/dbgfm. Please update both jts/dbgfm and bcgsc/abyss.

**Comment by rchikhi** [comment]
ok
