### ISSUE TITLE
error: ‘outBase’ may be used uninitialized in this function

### ISSUE THREAD

**Issue by rchikhi** [jts/dbgfm#4]
When I compile with CXXFLAGS including -Wall and -Werror (these flags are enabled in abyss-dbgfm), the following code cannot be compiled:

`fm_index.h:111: error: ‘outBase’ may be used uninitialized in this function`

This isn't a time-sensitive issue as I can just compile without these flags.

**Comment by sjackman** [comment]
I'm seeing the same error. The simple workaround is to initialize `outBase` to something, like '\0'.

https://github.com/jts/dbgfm/blob/master/fm_index.h#L111

**Comment by rchikhi** [comment]
thanks!
